const String ={
    hello:'hello',
    food:'food',
    Forgot:'Forgot your password ?',
    SIGN_IN:'SIGN IN',
    Or:'Or',
    Donthave:'Dont have an account?',
    SignUp:'Sign Up',
    Home:'Home',
    WhatWould:'What Would you like to eat?',
    Popluar:'Popluar Foods',
    SeeAll:'See All',
    FriedEgg:'Fried Egg',
    Mixed:'Mixed Vegetable',
    Best:'Best Foods',
    Login:'Login',
    Otp:'Otp',
    Grilled:'Grilled Salmon',
    $96:'$96.00',
    byPizza:'by Pizza hut',
    Add:'Add To Bag',
    Food_Detalis:'Food Detalis',
    Food_Reviews:'Food Reviews',
    Item:'item Carts',
    Your:'Your Food Carts',
    GrilledSalmon:'Grilled Salmon',
    $9600:'$96.00',
    AddTo2:'Add To 2',
    Meat:'Meat vegetable',
    Total:'Total',
    $192:'$192',
    $102:'$102',
    $292:'$292',
    Payment:'Payment Method',
    Credit:'Credit/Debit Card'

}
export default String